//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_To_chuc_thi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bai_lam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bai_lam()
        {
            this.ct_bai_lam = new HashSet<ct_bai_lam>();
        }
    
        public int id_bai_lam { get; set; }
        public System.DateTime gio_lam { get; set; }
        public System.DateTime gio_nop { get; set; }
        public int id_phieu_du_thi { get; set; }
    
        public virtual phieu_du_thi phieu_du_thi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ct_bai_lam> ct_bai_lam { get; set; }
    }
}
