//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_To_chuc_thi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bo_cau_hoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bo_cau_hoi()
        {
            this.Cau_hoi = new HashSet<Cau_hoi>();
        }
    
        public int id_bo_cau_hoi { get; set; }
        public string ten_bo_cau_hoi { get; set; }
        public int id_de_thi { get; set; }
    
        public virtual de_thi de_thi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cau_hoi> Cau_hoi { get; set; }
    }
}
