//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_To_chuc_thi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class de_thi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public de_thi()
        {
            this.bo_cau_hoi = new HashSet<bo_cau_hoi>();
            this.phieu_du_thi = new HashSet<phieu_du_thi>();
        }
    
        public int id_de_thi { get; set; }
        public string ma_de_thi { get; set; }
        public System.DateTime ngay_tao { get; set; }
        public int id_khung_de { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bo_cau_hoi> bo_cau_hoi { get; set; }
        public virtual khung_de_thi khung_de_thi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phieu_du_thi> phieu_du_thi { get; set; }
    }
}
