//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_To_chuc_thi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ket_qua
    {
        public int id_ket_qua { get; set; }
        public int diem { get; set; }
        public int id_lua_chon { get; set; }
        public int id_bai_lam { get; set; }
    
        public virtual ct_bai_lam ct_bai_lam { get; set; }
    }
}
