//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_To_chuc_thi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khung_de_thi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khung_de_thi()
        {
            this.de_thi = new HashSet<de_thi>();
        }
    
        public int id_khung_de { get; set; }
        public string ten_khung_de { get; set; }
        public int thoi_luong_thi { get; set; }
        public System.DateTime ngay_tao { get; set; }
        public int id_nguoi_dung { get; set; }
        public int id_mon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<de_thi> de_thi { get; set; }
        public virtual Nguoi_dung Nguoi_dung { get; set; }
        public virtual mon mon { get; set; }
    }
}
