//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_To_chuc_thi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nguoi_dung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nguoi_dung()
        {
            this.khung_de_thi = new HashSet<khung_de_thi>();
        }
    
        public int id_nguoi_dung { get; set; }
        public string ho_ten { get; set; }
        public System.DateTime ngay_sinh { get; set; }
        public System.DateTime ngay_vao_lam { get; set; }
        public bool gioi_tinh { get; set; }
        public string email { get; set; }
        public string mat_khau { get; set; }
        public bool tinh_trang { get; set; }
        public string sdt { get; set; }
        public string cmnd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<khung_de_thi> khung_de_thi { get; set; }
    }
}
