//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_To_chuc_thi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinh_vien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sinh_vien()
        {
            this.Thong_tin_hoc_phan = new HashSet<Thong_tin_hoc_phan>();
        }
    
        public string mssv { get; set; }
        public string ho_ten { get; set; }
        public System.DateTime ngay_sinh { get; set; }
        public bool gioi_tinh { get; set; }
        public string lop { get; set; }
        public string mat_khau { get; set; }
        public bool tinh_trang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Thong_tin_hoc_phan> Thong_tin_hoc_phan { get; set; }
    }
}
